<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- AndonTerminal: WinForms Application -->
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>AndonTerminal</RootNamespace>
    <AssemblyName>AndonTerminal</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>

  </PropertyGroup>

  <ItemGroup>
    <!-- Tham chiếu đến SharedLib -->
    <ProjectReference Include="..\SharedLib\SharedLib.csproj" />
  </ItemGroup>

</Project>
